"""added_is_active_column

Revision ID: 2ca6c95dd95b
Revises: bcb063b582c0
Create Date: 2026-01-04 21:00:58.319341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ca6c95dd95b'
down_revision: Union[str, Sequence[str], None] = 'bcb063b582c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
