"""add_escalation_model

Revision ID: 2e4c06d6829c
Revises: 2ca6c95dd95b
Create Date: 2026-01-18 10:39:32.721087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4c06d6829c'
down_revision: Union[str, Sequence[str], None] = '2ca6c95dd95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_business_id'), ['business_id'], unique=False)

    # op.drop_table('app_states')
    # op.drop_table('sessions')
    # op.drop_table('events')
    # op.drop_table('user_states')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_escalation_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('escalation_emails', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('escalation_emails')
        batch_op.drop_column('is_escalation_enabled')

    op.create_table('user_states',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('invocation_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('author', sa.VARCHAR(length=256), nullable=False),
    sa.Column('actions', sa.BLOB(), nullable=False),
    sa.Column('long_running_tool_ids_json', sa.TEXT(), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('grounding_metadata', sa.TEXT(), nullable=True),
    sa.Column('custom_metadata', sa.TEXT(), nullable=True),
    sa.Column('partial', sa.BOOLEAN(), nullable=True),
    sa.Column('turn_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('interrupted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['app_name', 'user_id', 'session_id'], ['sessions.app_name', 'sessions.user_id', 'sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'app_name', 'user_id', 'session_id')
    )
    op.create_table('sessions',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', 'id')
    )
    op.create_table('app_states',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_business_id'))

    op.drop_table('escalations')
    # ### end Alembic commands ###
