"""add_is_lead_to_guest_users

Revision ID: 35c884792568
Revises: 324a5f04668b
Create Date: 2025-12-25 21:41:16.330166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c884792568'
down_revision: Union[str, Sequence[str], None] = '324a5f04668b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lead', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.drop_column('is_lead')

    # ### end Alembic commands ###
