"""Add payment transactions table

Revision ID: 8837e83d7599
Revises: f8145458d71b
Create Date: 2026-02-08 19:19:06.778145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8837e83d7599'
down_revision: Union[str, Sequence[str], None] = 'f8145458d71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_reference'), ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_states',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name')
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('invocation_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('author', sa.VARCHAR(length=256), nullable=False),
    sa.Column('actions', sa.BLOB(), nullable=False),
    sa.Column('long_running_tool_ids_json', sa.TEXT(), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('grounding_metadata', sa.TEXT(), nullable=True),
    sa.Column('custom_metadata', sa.TEXT(), nullable=True),
    sa.Column('partial', sa.BOOLEAN(), nullable=True),
    sa.Column('turn_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=256), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('interrupted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['app_name', 'user_id', 'session_id'], ['sessions.app_name', 'sessions.user_id', 'sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'app_name', 'user_id', 'session_id')
    )
    op.create_table('user_states',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id')
    )
    op.create_table('sessions',
    sa.Column('app_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', 'id')
    )
    # ### end Alembic commands ###
