"""Add subscription fields

Revision ID: c202e6229725
Revises: 2e4c06d6829c
Create Date: 2026-02-02 20:09:44.693181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c202e6229725'
down_revision: Union[str, Sequence[str], None] = '2e4c06d6829c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(), nullable=False, server_default='spark'))
        batch_op.add_column(sa.Column('credits_balance', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('credits_last_refilled', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_escalations_used', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('total_escalations_used')
        batch_op.drop_column('credits_last_refilled')
        batch_op.drop_column('credits_balance')
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
