"""add webhook payload field

Revision ID: dae11b7e812a
Revises: e843c7b7d12a
Create Date: 2026-03-08 19:41:15.314722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dae11b7e812a'
down_revision: Union[str, Sequence[str], None] = 'e843c7b7d12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    existing = sa.inspect(conn).get_table_names()
    for tbl in ('user_states', 'app_states', 'events', 'sessions'):
        if tbl in existing:
            op.drop_table(tbl)
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_webhook_payload', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_column('raw_webhook_payload')

    op.create_table('sessions',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', 'id', name='sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('invocation_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('actions', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('long_running_tool_ids_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('grounding_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('partial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('turn_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('interrupted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_name', 'user_id', 'session_id'], ['sessions.app_name', 'sessions.user_id', 'sessions.id'], name=op.f('events_app_name_user_id_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'app_name', 'user_id', 'session_id', name=op.f('events_pkey'))
    )
    op.create_table('app_states',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', name=op.f('app_states_pkey'))
    )
    op.create_table('user_states',
    sa.Column('app_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', name=op.f('user_states_pkey'))
    )
    # ### end Alembic commands ###
