"""Add payment fields

Revision ID: f8145458d71b
Revises: c202e6229725
Create Date: 2026-02-02 22:07:13.553531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8145458d71b'
down_revision: Union[str, Sequence[str], None] = 'c202e6229725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_subscription_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('payment_subscription_id')
        batch_op.drop_column('payment_customer_id')
        batch_op.drop_column('payment_provider')

    # ### end Alembic commands ###
