"""Add WhatsApp fields to WidgetSettings

Revision ID: bbeea3a5121a
Revises: 69e84ea8a414
Create Date: 2025-12-21 21:36:03.999788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbeea3a5121a'
down_revision: Union[str, Sequence[str], None] = '69e84ea8a414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('whatsapp_enabled')

    # ### end Alembic commands ###
