"""Add widget tables

Revision ID: bcd65c085afb
Revises: 3b48f055a5f8
Create Date: 2025-12-08 01:34:00.846223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd65c085afb'
down_revision: Union[str, Sequence[str], None] = '3b48f055a5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('public_widget_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_settings_public_widget_id'), ['public_widget_id'], unique=True)

    op.create_table('guest_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('widget_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_messages')
    op.drop_table('guest_users')
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_settings_public_widget_id'))

    op.drop_table('widget_settings')
    # ### end Alembic commands ###
