"""Add analytics tables and columns

Revision ID: fb8ceff86cad
Revises: 1c6554b429e3
Create Date: 2025-12-13 14:44:19.981508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8ceff86cad'
down_revision: Union[str, Sequence[str], None] = '1c6554b429e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily_summary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_guests', sa.Integer(), nullable=True),
    sa.Column('new_guests', sa.Integer(), nullable=True),
    sa.Column('returning_guests', sa.Integer(), nullable=True),
    sa.Column('leads_captured', sa.Integer(), nullable=True),
    sa.Column('top_intent', sa.String(), nullable=True),
    sa.Column('top_location', sa.String(), nullable=True),
    sa.Column('top_referrer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referrer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_messages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_messages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_messages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('first_response_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_returning', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.drop_column('is_returning')
        batch_op.drop_column('total_sessions')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('first_seen_at')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('first_response_time')
        batch_op.drop_column('ai_messages')
        batch_op.drop_column('user_messages')
        batch_op.drop_column('total_messages')
        batch_op.drop_column('session_duration')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('referrer')
        batch_op.drop_column('timezone')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('os')
        batch_op.drop_column('browser')
        batch_op.drop_column('device_type')

    op.drop_table('analytics_daily_summary')
    # ### end Alembic commands ###
